### ISSUE TITLE
mainConfig is not defined

### ISSUE THREAD

**Issue by EcoDankMemer** [OpenWebControl/OpenWebControl#2]
It dont start up

**Comment by BasToTheMax** [comment]
Wich error do U get?

**Comment by EcoDankMemer** [comment]
![unknown](https://user-images.githubusercontent.com/93878599/143226508-685a0550-f081-42f1-8ad3-c804d40d856d.png)

**Comment by EcoDankMemer** [comment]
here

**Comment by BasToTheMax** [comment]
Fixed in #1df8a90
