### ISSUE TITLE
Session expire date always the same

### ISSUE THREAD

**Issue by BasToTheMax** [OpenWebControl/OpenWebControl#6]
When a new session is created the session expire date is **always** the same:

![image](https://user-images.githubusercontent.com/55401336/143295177-f36bc7cf-5d06-413d-bbc9-07fd044f81ad.png)

Sessions are created in the `lib/query.js` file!

**Comment by pratik12350** [comment]
There are two ways to do if think...

1: Use `setTimeout` (kinda buggy)
2: Don't use sessions, use IP address instead! @BasToTheMax

**Comment by BasToTheMax** [comment]
> There are two ways to do if think...
> 
> 1: Use `setTimeout` (kinda buggy) 2: Don't use sessions, use IP address instead! @BasToTheMax

1. setTimeout will not work if we scale the panel to multiple servers with a load balancer.
2. How would we use IP adresses. And I think everyone will have the same IP address, because I proxy all the requests via NGINX

**Comment by BasToTheMax** [comment]
Fixed!
