### ISSUE TITLE
Hashing passwords for accounts

### ISSUE THREAD

**Issue by tlkh40** [OpenWebControl/OpenWebControl#8]
**Problem**
Currently the passwords aren't hashed, this means if someone was able to hack the database, hackers could get access to the actual password of users very easy. Users usually have same password on multiple platforms / accounts. By hashing the passwords and salting them, the hacker needs to bruteforce the password and that will take longer which give time for the user to change their passwords.

**Solution**
I suggest using argon2 and salting the password

**Comment by Bobu5** [comment]
i agri

**Comment by BasToTheMax** [comment]
What about using md5? And then using an API to check public md5 databases to check if the password is already in it, so the user doesn't use a password that is already leaked.

**Comment by tlkh40** [comment]
I think thats a password manager's job to do. Also don't reccomend uhh using md5 as a hash or sending hashed passwords to any type of public database md5 things.

**Comment by BasToTheMax** [comment]
1. Why do U not recommend md5?
2. Oke

**Comment by tlkh40** [comment]
MD5 is weak. You should atleast use something like bcrypt if argon2 is too slow for you.

**Comment by BasToTheMax** [comment]
what about sha-265

**Comment by tlkh40** [comment]
please just use [this](https://www.npmjs.com/package/bcrypt). im confused on why do you wanna use sha-256 or md5

**Comment by pratik12350** [comment]
@BasToTheMax Yes we should use argon2, MD5 is weak. And argon2 is easy too just look at [their npm](https://npmjs.com/package/argon2) !!
And fast! We have to revive this projec!1!!!!!1

**Comment by BasToTheMax** [comment]
Oke

**Comment by QuikBolte** [comment]
+1

**Comment by pratik12350** [comment]
This project was dead. Me and @BasToTheMax are reviving it and we will make sure to hash password this time! 😅 Closing issue!
